[membership]
title = "V LIVE ─ STORE ─ MEMBERSHIP"
url = "https://www.vlive.tv/vstore/membership"
entrySelector = "ul.channel_fanship_list._mem_list li"
titleSelector = "strong.title"
linkSelector = "a.store_fanship_card"
contentSelector = "em.icon_fanship"
imageSelector = "div.thumb_area img"
waitUntil = "networkidle"

[video]
title = "V LIVE ─ STORE ─ V LIVE+"
url = "https://www.vlive.tv/vstore/video"
entrySelector = "ul.best_package_list li"
titleSelector = "strong.info_tit"
linkSelector = "a.store_fanship_card"
contentSelector = "div.info_date span.date"
imageSelector = "div.thumb_area img"
waitUntil = "networkidle"